### ISSUE TITLE
[BUG] Install target fails on K3s v1.18.9

### ISSUE THREAD

**Issue by shmileee** [Dysproz/DaemonJob#4]
**Describe the bug**
`make install` fails on K3s v1.18.9-rc1+k3s1 amd64 with the following:
```
/home/es/go/bin/kustomize build config/crd | kubectl apply -f -
The CustomResourceDefinition "daemonjobs.dj.dysproz.io" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
make: *** [Makefile:41: install] Error 1
```

**To Reproduce**
1. Run: `make kustomize` to install kustomize
2. Run: `make controller-gen` to install controller-gen
3. Run: `make manifests` to generate manifests
4. Run: `make install` to apply manifests

**Expected behavior**
CRDs are installed.

**Environment:**
 - Kubernetes version:
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9-rc1+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T01:49:08Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
 - Kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Dysproz** [comment]
Thanks for your submission!
I've done some research and it seems to be a common problem for Kubernetes >= 1.18 (https://github.com/kubernetes/kubernetes/issues/91395).
I've manually added structures for Pod template spec and removed protocol from x-kubernetes-list-map-keys which makes it work for newer Kubernetes version up to the time when they'll fix it officialy.

Check if it works for you and let me know. :)
